### ISSUE TITLE
Empty password works for crackme02

### ISSUE THREAD

**Issue by bradain** [LeoTindall/crackmes#2]
Hi Leo,
Nice work on the tutorial!

You mentioned the incremental nature of the crackme02 password (first letter alone works, first 2 letters, first 3 letters). Its also interesting that an empty password works for the same reason.
`   ./crackme02.64 "" `
`   Yes,  is correct!`
regards
Bradain

**Comment by NoraCodes** [comment]
Good point. I'll mention this in the tutorial.
