### ISSUE TITLE
Make with no arguments should make-all

### ISSUE THREAD

**Issue by fake-name** [LeoTindall/crackmes#4]
Basically the title. Is there a reason `make all` doesn't work, and `make` seems to actually trigger `make clean`?

My naive impression was that `make` with no arguments should build everything.

**Comment by NoraCodes** [comment]
You're right, that is the expected behavior. I'll fix this tomorrow.

**Comment by NoraCodes** [comment]
Actually, never mind; this is fixed in a1b4437 so I'll close this. Thanks for reporting it!

**Comment by fake-name** [comment]
Heh, wow, that took far too long to be resolved! /s

Thanks!
