### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by ggljzr** [LeoTindall/crackmes#6]
Hi,

there's maybe a typo in tutorial:
<details><summary>Spoiler alert</summary>
<p>

>This is really all we need. Simply adding one to each letter of password1 in ASCII gives us “o`rrvnqc0”.

I guess it should be "subtracting one". Same for reversed code:

```
if (argv[1][i] != comparison[i] + 1)
```

should be

```
if (argv[1][i] != comparison[i] - 1)
```

as it is in `crackme02.c`.
</p>
</details>

**Comment by NoraCodes** [comment]
You're right, I'll fix this ASAP. Thanks.
