### ISSUE TITLE
crackme02 can be solved with multiple solutions not intended to be viable (i think)

### ISSUE THREAD

**Issue by mariopepe** [LeoTindall/crackmes#7]
First of all let me saying I'm enjoying this tutorial series just AF so thanks a lot!

I don't know if this is an issue or not (in case i hope you will accept my aplogize), but i will leave it here for you to check.

The thing is this, looking at control flow graph generated with radare2, I noticed that immediately after the check for the correct number of arguments, there was a "shortcut" (highlighted in yellow in the picture) to the "is correct" statement.
In fact the flow reaches the "is correct" statement immediately if the the result of `test al, al` is positive, and since the `al` register is determined by the user input, if the user input the NUL character ( `''` ) the flow will reach "is correct".
Also further analysis made me discover that it will accept not only o'rrvnqc0' but also all of this:
o
o'
o'r
o'rr
o'rrv
o'rrvn
o'rrvnq
o'rrvnqc
o'rrvnqc0
and as said before it will also accept:
''

After i found this, I looked at the code and I think it makes sense; I can't wait to know your opinion about this. Thanks again 😄

![graph copy](https://user-images.githubusercontent.com/14803862/39335797-cf7a03de-49b4-11e8-94f4-e9c0a8bc2b59.png)

**Comment by NoraCodes** [comment]
Congrats on finding this. It's in fact intended, so that clever reverse engineers such as yourself can find a shortcut in this exercise :)

I'm glad you're enjoying the tutorial!
